### ISSUE TITLE
blips in FG sim

### ISSUE THREAD

**Issue by adampbeardsley** [HERA-Team/hera_sim#34]
When making a foreground sim, @lwhitler saw random little blips in her waterfalls. For example:
![image](https://user-images.githubusercontent.com/4752917/55173906-bbf6a500-5139-11e9-8986-5e5f586083f7.png)

Hopefully Lily can fill in more how she created this sim, and provide a MWE.

**Comment by lwhitler** [comment]
It turns out that I accidentally left RFI in. Specifically, the little blips in the waterfall Adam posted were from what hera_sim is calling rfi_scatter. Without RFI, it's behaving as expected; the horizontal line here in the bottom panel is from rfi_impulse.

![image](https://user-images.githubusercontent.com/25778615/55267906-84275480-5242-11e9-818f-9c5577c0021b.png)
