### ISSUE TITLE
Update `rfi.rfi_dtv`

### ISSUE THREAD

**Issue by r-pascua** [HERA-Team/hera_sim#51]
There is a slight bug with how `rfi.rfi_dtv` works regarding how DTV bands are handled. This should be fixed. It is currently handled with a `try: except:` clause, but should be handled in a better way.

**Comment by steven-murray** [comment]
Copying a comment on a recent PR concerning this issue: (we need to) scroll through all bands, and if its close enough or within `fqs`, do what is necessary, and otherwise just warn the user -- it's likely that if this happens they have done something wrong themselves.

In this case, you have to special case where band is less than `fqs.min() - width`, and warn the user. Also special-case where band is between `fqs.min() - width` and `fqs.min()`, and use the first few indices.

**Comment by r-pascua** [comment]
Issue fixed in PR #53.
